[package]
name = "gamepad_input"
version = "0.1.0"
edition = "2021"
link = "Xinput"

[dependencies]
windows_error_handling = {version = "0.1.0", git = "https://github.com/NikhilNathanael/windows_error_handling"}
